### ISSUE TITLE
Error in array index.

### ISSUE THREAD

**Issue by Dantara** [madnight/asciichart#1]
The `plot` function throws `Error in array index` in case of zero or one element in the list in its argument.

**Comment by Dantara** [comment]
Also, the same error will be thrown if all elements are equal. Example: `plot [1,1,1,1]`.

**Comment by madnight** [comment]
Fixed in https://github.com/madnight/asciichart/commit/49cc4108149b0f782dba455809191302b9252bee

Thx for report!
